package xxatcust.oracle.apps.sudoku.model.readonlyvo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 15 18:28:36 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CFDReportVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CFDReportVOImpl() {
    }
}
