package xxatcust.oracle.apps.sudoku.model.readonlyvo;

import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 25 20:48:46 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SalesChannelDefaultUsrPrefVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        SalesChannel {
            public Object get(SalesChannelDefaultUsrPrefVORowImpl obj) {
                return obj.getSalesChannel();
            }

            public void put(SalesChannelDefaultUsrPrefVORowImpl obj,
                            Object value) {
                obj.setSalesChannel((String)value);
            }
        }
        ,
        PaymentTerm {
            public Object get(SalesChannelDefaultUsrPrefVORowImpl obj) {
                return obj.getPaymentTerm();
            }

            public void put(SalesChannelDefaultUsrPrefVORowImpl obj,
                            Object value) {
                obj.setPaymentTerm((String)value);
            }
        }
        ,
        IncoTerm {
            public Object get(SalesChannelDefaultUsrPrefVORowImpl obj) {
                return obj.getIncoTerm();
            }

            public void put(SalesChannelDefaultUsrPrefVORowImpl obj,
                            Object value) {
                obj.setIncoTerm((String)value);
            }
        }
        ,
        Currency {
            public Object get(SalesChannelDefaultUsrPrefVORowImpl obj) {
                return obj.getCurrency();
            }

            public void put(SalesChannelDefaultUsrPrefVORowImpl obj,
                            Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        CustomerName {
            public Object get(SalesChannelDefaultUsrPrefVORowImpl obj) {
                return obj.getCustomerName();
            }

            public void put(SalesChannelDefaultUsrPrefVORowImpl obj,
                            Object value) {
                obj.setCustomerName((String)value);
            }
        }
        ,
        RowVal {
            public Object get(SalesChannelDefaultUsrPrefVORowImpl obj) {
                return obj.getRowVal();
            }

            public void put(SalesChannelDefaultUsrPrefVORowImpl obj,
                            Object value) {
                obj.setRowVal((String)value);
            }
        }
        ,
        BusinessAgreement {
            public Object get(SalesChannelDefaultUsrPrefVORowImpl obj) {
                return obj.getBusinessAgreement();
            }

            public void put(SalesChannelDefaultUsrPrefVORowImpl obj,
                            Object value) {
                obj.setBusinessAgreement((String)value);
            }
        }
        ,
        CurrencyVA {
            public Object get(SalesChannelDefaultUsrPrefVORowImpl obj) {
                return obj.getCurrencyVA();
            }

            public void put(SalesChannelDefaultUsrPrefVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IncoTermVA {
            public Object get(SalesChannelDefaultUsrPrefVORowImpl obj) {
                return obj.getIncoTermVA();
            }

            public void put(SalesChannelDefaultUsrPrefVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PaymentTermsVA {
            public Object get(SalesChannelDefaultUsrPrefVORowImpl obj) {
                return obj.getPaymentTermsVA();
            }

            public void put(SalesChannelDefaultUsrPrefVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SalesChannelVA {
            public Object get(SalesChannelDefaultUsrPrefVORowImpl obj) {
                return obj.getSalesChannelVA();
            }

            public void put(SalesChannelDefaultUsrPrefVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        businessAgreementVA {
            public Object get(SalesChannelDefaultUsrPrefVORowImpl obj) {
                return obj.getbusinessAgreementVA();
            }

            public void put(SalesChannelDefaultUsrPrefVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CustomerNameVA {
            public Object get(SalesChannelDefaultUsrPrefVORowImpl obj) {
                return obj.getCustomerNameVA();
            }

            public void put(SalesChannelDefaultUsrPrefVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(SalesChannelDefaultUsrPrefVORowImpl object);

        public abstract void put(SalesChannelDefaultUsrPrefVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SALESCHANNEL = AttributesEnum.SalesChannel.index();
    public static final int PAYMENTTERM = AttributesEnum.PaymentTerm.index();
    public static final int INCOTERM = AttributesEnum.IncoTerm.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int ROWVAL = AttributesEnum.RowVal.index();
    public static final int BUSINESSAGREEMENT = AttributesEnum.BusinessAgreement.index();
    public static final int CURRENCYVA = AttributesEnum.CurrencyVA.index();
    public static final int INCOTERMVA = AttributesEnum.IncoTermVA.index();
    public static final int PAYMENTTERMSVA = AttributesEnum.PaymentTermsVA.index();
    public static final int SALESCHANNELVA = AttributesEnum.SalesChannelVA.index();
    public static final int BUSINESSAGREEMENTVA = AttributesEnum.businessAgreementVA.index();
    public static final int CUSTOMERNAMEVA = AttributesEnum.CustomerNameVA.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SalesChannelDefaultUsrPrefVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute SalesChannel.
     * @return the SalesChannel
     */
    public String getSalesChannel() {
        
        
        return (String) getAttributeInternal(SALESCHANNEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SalesChannel.
     * @param value value to set the  SalesChannel
     */
    public void setSalesChannel(String value) {
        setAttributeInternal(SALESCHANNEL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PaymentTerm.
     * @return the PaymentTerm
     */
    public String getPaymentTerm() {
        return (String) getAttributeInternal(PAYMENTTERM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PaymentTerm.
     * @param value value to set the  PaymentTerm
     */
    public void setPaymentTerm(String value) {
        setAttributeInternal(PAYMENTTERM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IncoTerm.
     * @return the IncoTerm
     */
    public String getIncoTerm() {
        return (String) getAttributeInternal(INCOTERM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IncoTerm.
     * @param value value to set the  IncoTerm
     */
    public void setIncoTerm(String value) {
        setAttributeInternal(INCOTERM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Currency.
     * @return the Currency
     */
    public String getCurrency() {
        return (String) getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Currency.
     * @param value value to set the  Currency
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerName.
     * @return the CustomerName
     */
    public String getCustomerName() {
        return (String) getAttributeInternal(CUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerName.
     * @param value value to set the  CustomerName
     */
    public void setCustomerName(String value) {
        setAttributeInternal(CUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RowVal.
     * @return the RowVal
     */
    public String getRowVal() {
        return (String) getAttributeInternal(ROWVAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RowVal.
     * @param value value to set the  RowVal
     */
    public void setRowVal(String value) {
        setAttributeInternal(ROWVAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BusinessAgreement.
     * @return the BusinessAgreement
     */
    public String getBusinessAgreement() {
        return (String) getAttributeInternal(BUSINESSAGREEMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BusinessAgreement.
     * @param value value to set the  BusinessAgreement
     */
    public void setBusinessAgreement(String value) {
        setAttributeInternal(BUSINESSAGREEMENT, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CurrencyVA.
     */
    public RowSet getCurrencyVA() {
        return (RowSet)getAttributeInternal(CURRENCYVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> IncoTermVA.
     */
    public RowSet getIncoTermVA() {
        return (RowSet)getAttributeInternal(INCOTERMVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PaymentTermsVA.
     */
    public RowSet getPaymentTermsVA() {
        return (RowSet)getAttributeInternal(PAYMENTTERMSVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SalesChannelVA.
     */
    public RowSet getSalesChannelVA() {
        return (RowSet)getAttributeInternal(SALESCHANNELVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> businessAgreementVA.
     */
    public RowSet getbusinessAgreementVA() {
        return (RowSet)getAttributeInternal(BUSINESSAGREEMENTVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CustomerNameVA.
     */
    public RowSet getCustomerNameVA() {
        return (RowSet)getAttributeInternal(CUSTOMERNAMEVA);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
