package xxatcust.oracle.apps.sudoku.model.readonlyvo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 15 17:00:20 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXATGlobalDirRVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XXATGlobalDirRVOImpl() {
    }
}
